### ISSUE TITLE
Rebuild documentation for Fedora 28

### ISSUE THREAD

**Issue by imsedgar** [clumens/pykickstart#220]
http://pykickstart.readthedocs.io/ contains a version that does not reflect the changes that are in Fedora 28.
For example, options auth and authconfig are no longer usable in Fedora 28, they are replaced by authselect. This change should be described in the docs.

**Comment by M4rtinK** [comment]
The documentation on RTD should rebuild automatically via webhook when changes happen in the master branch and these (and other) changes definitely went to the master branch.

But looking at the builds list, this is apparently not happening:
http://readthedocs.org/projects/pykickstart/builds/

The latest build seems to have happened 2 months, 3 weeks ago, which would correspond to the outdated docs you are seeing.

@clumens Maybe some more fallout from moving the repo (eq. RTD does not follow the redirects for some reason) from the rhinstaller group ?

**Comment by clumens** [comment]
Thanks for pointing this out - I've changed the URL in RTD and it's working on a new build, so we'll see what happens.  I'll try to come up with something dumb to push later today to see if it happens automatically, too.

**Comment by clumens** [comment]
Looks like it's being built automatically.
